INSERT INTO `interface_info` VALUES ('1', 'ewqe', 'se', 'sq', 'wrqw', 'er', '1', '0');
INSERT INTO `interface_info` VALUES ('2', 'aaa', 'post', 'aaa', null, '	\n					a;', '1', '0');
INSERT INTO `interface_info` VALUES ('3', 'aaa', 'post', 'aaa', null, '	\n					a;', '1', '0');
INSERT INTO `interface_info` VALUES ('4', 'aaa', 'post', 'aaa', null, '	\n					a;', '1', '0');
INSERT INTO `interface_info` VALUES ('5', 'aaa', 'get', 'aaa', null, '	\n					jjjj', '1', '0');
INSERT INTO `interface_info` VALUES ('6', 'aaa', 'get', 'aaa', null, '	\n					jjjj', '1', '0');
INSERT INTO `interface_info` VALUES ('7', 'fff', 'get', 'fff', null, '	\n					fff', '1', '0');
INSERT INTO `interface_info` VALUES ('8', 'fff', 'get', 'fff', null, '	\n					fff', '1', '0');
INSERT INTO `interface_info` VALUES ('9', '', 'get', '', null, '	\n					', '1', '0');
INSERT INTO `interface_info` VALUES ('10', 'a', 'get', 'a', 'a', '	\n					d ', '26', '1');
INSERT INTO `interface_info` VALUES ('11', 'FF', 'get', 'FF', 'FF', '	\n					FFF', '26', '1');
INSERT INTO `interface_info` VALUES ('12', 'GG', 'get', 'FF', 'FFGG', '	\n					FFF', '26', '1');
INSERT INTO `interface_info` VALUES ('13', 'GGGGG', 'get', 'FF', 'FFGG', '	\n					FFF', '26', '0');
INSERT INTO `interface_info` VALUES ('14', 'GGGGG', 'get', 'FF', 'FFGG', '	\n					FFF', '26', '1');
INSERT INTO `interface_info` VALUES ('15', 'GGGGG', 'get', 'FF', 'FFGGGG', '	\n					FFF', '26', '1');
INSERT INTO `interface_info` VALUES ('16', '姚秋红', 'get', 'hhh', 'url', 'hhhh', '26', '0');
INSERT INTO `interface_info` VALUES ('17', '姚秋红', 'get', '啊', 'uil', '	\n					jjjj', '126', '1');
INSERT INTO `interface_info` VALUES ('18', 'ggg', 'get', 'gggg', 'ggg', '	\n					ggg', '126', '1');
INSERT INTO `interface_info` VALUES ('19', 'aaa', 'get', 'aaa', 'aaa', '	\n			aa		', '126', '1');
INSERT INTO `interface_info` VALUES ('20', 'hhhh', 'get', 'hhhh', 'hhhh', '	\n					hhhh', '126', '0');
